name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21 from jdk.java.net
        uses: actions/setup-java@v2
        with:
          java-version: 21-ea
          distribution: temurin
      - name: Build with Maven
        run: mvn --batch-mode verify
