name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dnet.bytebuddy.experimental=true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21 from jdk.java.net
        uses: oracle-actions/setup-java@v1
        with:
            website: jdk.java.net
            release: 21
      - name: Build with Maven
        run: mvn --batch-mode verify
